### ISSUE TITLE
bug: E-1 In this state, git should have been sync with the remote, but it is not, this is caused by proce

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyGit-Desktop#100]
## Environment

TiddlyGit 0.4.2
Electron 14.0.0-beta.19
darwin 20.6.0
Locale: zh-CN

## Description:

应该自动 push 上去

## Steps to Reproduce:

这个状态的时候打开 TG

<img width="617" alt="截屏2021-08-20 上午10 47 43" src="https://user-images.githubusercontent.com/3746270/130171264-27e8d679-8bda-4ef0-8038-1f1795d7207a.png">

## Additional Context

```typescript
AssumeSyncError: E-1 In this state, git should have been sync with the remote, but it is not, this is caused by procedural bug in the git-sync-js. 
    at new t (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/errors.js:38:28)
    at Object.call (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/inspect.js:264:27)
    at step (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/inspect.js:33:23)
    at Object.next (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/inspect.js:14:53)
    at u (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/inspect.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

---

**Comment by linonetwo** [comment]
感觉应该在 GitPushFailed 的时候弹框提示用户重新登录一下，而不是直接把 E-1 甩出来

**Comment by linonetwo** [comment]
是因为token过期
