### ISSUE TITLE
bug: can't sync using scm plugin's button

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyGit-Desktop#101]
## Environment

TG Version v

Electron Version:

Node Version:

Chromium Version:

OS (macOS, Windows, Linux) and Version:

## Description:

```
{"message":"E-2 We need accessToken to sync to the cloud, you should pass accessToken as parameters in userInfo.","level":"error","timestamp":"2021-08-21T15:50:27.003Z"}
{"message":"↑Translated→: E-2 We need accessToken to sync to the cloud, you should pass accessToken as parameters in userInfo.","level":"error","timestamp":"2021-08-21T15:50:27.004Z"}
{"message":"E-0 IPC Error on GitChannel {\"type\":\"apply\",\"propKey\":\"commitAndSync\",\"args\":[\"/Users/linonetwo/Desktop/wiki\",\"https://github.com/linonetwo/wiki\"]} E-2 We need accessToken to sync to the cloud, you should pass accessToken as parameters in userInfo. SyncParameterMissingError: E-2 We need accessToken to sync to the cloud, you should pass accessToken as parameters in userInfo.\n    at new t (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/errors.js:51:28)\n    at call (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:142:31)\n    at step (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:43:23)\n    at Object.next (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:24:53)\n    at /Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:18:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:14:12)\n    at commitAndSync (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/git-sync-js/dist/index.js:133:12)\n    at e._subscribe (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/src/services/git/gitWorker.ts:34:14)\n    at e._trySubscribe (/Applications/TiddlyGit.app/Contents/Resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)","level":"error","timestamp":"2021-08-21T15:50:27.005Z"}
```

**Comment by linonetwo** [comment]
而且希望能拉取线上变更

**Comment by linonetwo** [comment]
现在也检测不到是不是有 commit 但没有 push 的信息

**Comment by linonetwo** [comment]
拉取先不做了，没空了。
