### ISSUE TITLE
bug: Tiddlywiki booted failed with error Unexpected end of JSON input SyntaxError: Unexpected end of JSON

### ISSUE THREAD

**Issue by L-M-Sherlock** [tiddly-gittly/TiddlyGit-Desktop#116]
## Environment

TiddlyGit 0.5.3
Electron 15.0.0
darwin 20.6.0
Locale: zh-CN

## Description:

强制关闭 TiddlyGit 后，重新打开就报错了。

## Additional Context

```typescript
Error: Tiddlywiki booted failed with error Unexpected end of JSON input SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at $tw.Wiki.application/json (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1621:16)
    at $tw.Wiki.deserializeTiddlers (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1516:23)
    at Object.$tw.loadTiddlersFromFile (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1796:23)
    at Object.$tw.loadTiddlersFromPath (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1848:22)
    at /Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1843:40
    at Object.$tw.utils.each (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:126:12)
    at Object.$tw.loadTiddlersFromPath (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1841:15)
    at Object.$tw.loadWikiTiddlers (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:2129:21)
    at Object.$tw.loadTiddlersNode (/Applications/TiddlyGit.app/Contents/Resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:2220:27)
    at Object.call (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/src/services/wiki/index.ts:137:22)
    at notifySubscription (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:103:23)
    at onNotify (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:144:5)
    at b.next (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:178:19)
    at Object.call (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/threads/dist/observable-promise.js:40:38)
    at notifySubscription (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:103:23)
    at onNotify (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:144:5)
    at b.call (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:178:19)
    at notifySubscription (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:103:23)
    at onNotify (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:144:5)
    at b.next (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:178:19)
    at O.call (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/subject.js:24:22)
    at notifySubscription (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:103:23)
    at onNotify (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:144:5)
    at b.next (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/observable-fns/dist.esm/observable.js:178:19)
    at i (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/node_modules/threads/dist/master/invocation-proxy.js:45:34)
```

---

**Comment by L-M-Sherlock** [comment]
> 这些都是tw本身的报错，你得发一下你git里的变更，看看是哪个文件的问题。
> 
> 看看是哪个json格式不对吗？

大海捞针啊。。。我回退版本了，现在没事了
