### ISSUE TITLE
bug: when open in new window, Unexpected token b in JSON at position 0

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyGit-Desktop#142]
## Environment

TiddlyGit 0.6.4
Electron 15.3.0
darwin 21.1.0
Locale: zh-CN

## Additional Context

```typescript
SyntaxError: Unexpected token b in JSON at position 0
    at JSON.parse (<anonymous>)
    at openInNewWindow (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/src/services/view/setupViewEventHandlers.ts:321:16)
    at Yo (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/src/services/view/setupViewEventHandlers.ts:373:5)
    at runMicrotasks (<anonymous>)
    at process._postBody (node:internal/process/task_queues:96:5)
    at Object.<anonymous> (/Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/webpack:/TiddlyGit/src/services/view/setupViewEventHandlers.ts:203:7)
```

---

**Comment by alexinea** [comment]
This happened to me too.

Windows 11
TiddlyGit 0.6.4
