### ISSUE TITLE
bug: Unexpected token b in JSON at position 0

### ISSUE THREAD

**Issue by AizawaAyame** [tiddly-gittly/TiddlyGit-Desktop#152]
## Environment

TiddlyGit 0.6.4
Electron 15.3.0
win32 10.0.19043
Locale: zh-CN

## Additional Context

```typescript
SyntaxError: Unexpected token b in JSON at position 0
    at JSON.parse (<anonymous>)
    at openInNewWindow (C:\Users\CenterK\AppData\Local\TiddlyGit\app-0.6.4\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\services\view\setupViewEventHandlers.ts:321:16)
    at Yo (C:\Users\CenterK\AppData\Local\TiddlyGit\app-0.6.4\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\services\view\setupViewEventHandlers.ts:373:5)
    at process._postBody (node:internal/process/task_queues:96:5)
    at Object.<anonymous> (C:\Users\CenterK\AppData\Local\TiddlyGit\app-0.6.4\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\services\view\setupViewEventHandlers.ts:203:7)
```

---

**Comment by linonetwo** [comment]
Hi, I might fixed this in [https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.6.5-a1](https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.6.5-a1) , could you give it a try?

**Comment by linonetwo** [comment]
And  Steps to Reproduc ?

**Comment by AizawaAyame** [comment]
yes, thanks very much.



***@***.***
 
From: lin onetwo
Date: 2021-12-08 10:56
To: tiddly-gittly/TiddlyGit-Desktop
CC: AizawaAyame; Author
Subject: Re: [tiddly-gittly/TiddlyGit-Desktop] bug: Unexpected token b in JSON at position 0 (Issue #152)
And  Steps to Reproduc ?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
