### ISSUE TITLE
Error: EROFS: read-only file system (Snap and AppImage)

### ISSUE THREAD

**Issue by ydewit** [tiddly-gittly/TiddlyGit-Desktop#28]
## Environment

Ubuntu 20.04 LTS

Version v0.2.1

## Description:

Download and run the AppImage or instance the snap package and you get the following exception in the console:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EROFS: read-only file system, mkdir '/tmp/.mount_Tiddly0GVvKP/logs/'
    at Object.mkdirSync (fs.js:823:3)
    at /tmp/.mount_Tiddly0GVvKP/resources/app.asar/node_modules/file-stream-rotator/FileStreamRotator.js:654:20
    at Array.reduce (<anonymous>)
    at mkDirForFile (/tmp/.mount_Tiddly0GVvKP/resources/app.asar/node_modules/file-stream-rotator/FileStreamRotator.js:642:27)
    at Object.FileStreamRotator.getStream (/tmp/.mount_Tiddly0GVvKP/resources/app.asar/node_modules/file-stream-rotator/FileStreamRotator.js:519:5)
    at new DailyRotateFile (/tmp/.mount_Tiddly0GVvKP/resources/app.asar/node_modules/winston-daily-rotate-file/daily-rotate-file.js:80:57)
    at Object.<anonymous> (/tmp/.mount_Tiddly0GVvKP/resources/app.asar/build/libs/log/index.js:10:5)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
```

**Comment by ydewit** [comment]
I am not sure about AppImage's, but it seems that Snap has a standard way of dealing with this since all executable live in a RO file-system. For example, see: https://snapcraft.io/docs/environment-variables and more specifically SNAP_DATA: it seems that we want to use this as your data folder. I am not sure about logs, though, and whether there is a standard location for those.

**Comment by linonetwo** [comment]
I tried to change the log folder in Linux, maybe you can try out latest version.

**Comment by ydewit** [comment]
It works now:
```
(node:124858) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Gtk-Message: 01:11:33.603: Failed to load module "appmenu-gtk-module"
```

**Comment by linonetwo** [comment]
@ydewit that warning is ok, it is caused by 3rd party libraries.

Glad to see this works in Linux, there are still some bugs as this is in alpha, It will take some time to improve it. I don't have much spare time these days.
