### ISSUE TITLE
bug: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().

### ISSUE THREAD

**Issue by Deteriorator** [tiddly-gittly/TiddlyGit-Desktop#52]
```
Error: Timeout: Did not receive an init message from worker after 10000ms. Make sure the worker calls expose().
    at Timeout._onTimeout (C:\Users\yuliang\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\main\index.js:2:1324935)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

---

TiddlyGit 0.4.0
Electron 12.0.6
win32 10.0.19042
Locale: zh-CN

I have reported two issues, but this issue may be different from the issues I have reported, so I create the issue

**Comment by linonetwo** [comment]
Hope this is fixed in the latest prerelease...

Cause might be the git-worker.
