### ISSUE TITLE
bug: getWorkspacesRemote Unable to find path to repository on disk

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/TiddlyGit-Desktop#53]
## Environment

Electron Version:

Node Version:

Chromium Version:

OS (macOS, Windows, Linux) and Version:

## Description:

{"message":"E-0 IPC Error on GitChannel {\"type\":\"apply\",\"propKey\":\"getWorkspacesRemote\",\"args\":[\"\"]} Unable to find path to repository on disk. Error: Unable to find path to repository on disk.\n    at /Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/index.js:2:270590\n    at exithandler (child_process.js:324:5)\n    at ChildProcess.errorhandler (child_process.js:336:5)\n    at ChildProcess.emit (events.js:315:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)\n    at onErrorNT (internal/child_process.js:465:16)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","level":"error"}
{"message":"E-0 IPC Error on GitChannel {\"type\":\"apply\",\"propKey\":\"getWorkspacesRemote\",\"args\":[\"/Users/linonetwo/Desktop\"]} Git could not be found at the expected path: '/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging. Error: Git could not be found at the expected path: '/node_modules/dugite/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.\n    at /Applications/TiddlyGit.app/Contents/Resources/app.asar/.webpack/main/index.js:2:270590\n    at exithandler (child_process.js:324:5)\n    at ChildProcess.errorhandler (child_process.js:336:5)\n    at ChildProcess.emit (events.js:315:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)\n    at onErrorNT (internal/child_process.js:465:16)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","level":"error"}

**Comment by linonetwo** [comment]
I think it is fixed in https://github.com/tiddly-gittly/TiddlyGit-Desktop/commit/ccaa979895c7ed5e3f29b6cb1267342305007211
