### ISSUE TITLE
bug: Error processing argument at index 2, conversion failure from 

### ISSUE THREAD

**Issue by Peckystudios** [tiddly-gittly/TiddlyGit-Desktop#57]
Mac mini M1版本
bug回報
第一次開啓

```
TypeError: Error processing argument at index 2, conversion failure from 
    at Object.normal (electron/js2c/browser_init.js:81:444)
    at Object.insertItemByType (electron/js2c/browser_init.js:81:1392)
    at Object.a.insert (electron/js2c/browser_init.js:81:3975)
    at Object.a.append (electron/js2c/browser_init.js:81:3639)
    at electron/js2c/browser_init.js:81:5650
    at Array.forEach (<anonymous>)
    at Function.a.buildFromTemplate (electron/js2c/browser_init.js:81:5600)
    at new MenuItem (electron/js2c/browser_init.js:73:587)
    at electron/js2c/browser_init.js:81:5657
    at Array.forEach (<anonymous>)
    at Function.a.buildFromTemplate (electron/js2c/browser_init.js:81:5600)
    at Ie.buildMenu (/Applications/TiddlyGit 2.app/Contents/Resources/app.asar/.webpack/main/index.js:2:1591005)
```

---

TiddlyGit 0.4.0
Electron 12.0.6
darwin 20.3.0
Locale: en-US

**Comment by linonetwo** [comment]
Get it, 应该是创建目录的时候，有时候时序有问题，才会有时候报有时候不报。我就没咋遇到过。

这个应该好修

**Comment by Peckystudios** [comment]
可能我有自己裝過官方Node js 版Tiddlywiki
或是我有裝過你的上一版（一直沒有成功打開）

後來報錯完app有成功打開新的Wiki

我剛剛看到下面issue 說可以把這個包成ipa
請問怎麼包呢？
我不是coder所以沒包過app
他上面寫的是把url放進去

謝謝你開發這個App！
還在研究玩耍中！

**Comment by Peckystudios** [comment]
我剛剛發現小飛魚不能提供中國以外區域使用（沒有手機！)

**Comment by linonetwo** [comment]
小飞鱼是啥呀？

**Comment by linonetwo** [comment]
我这个是电脑版的应用，应该没法包装成 ipa 给手机用的吧？

**Comment by Peckystudios** [comment]
我是在 issue #41 看到的
也許我誤會了什麼🤔

**Comment by linonetwo** [comment]
Oh，那个还待研究，需要很多开发量的

**Comment by Peckystudios** [comment]
好的，謝謝🙏

也不希望給你太大壓力哈哈

之後有更新我會來玩的～
謝謝你

**Comment by Peckystudios** [comment]
又發現一個bug
我重新啓動app之後
一樣報錯之後
進到app畫面就全白
點擊wiki打不開～
不知道是什麼問題

![image](https://user-images.githubusercontent.com/84195047/120917847-0396f500-c6e4-11eb-9c3e-4da9d608b216.png)

**Comment by linonetwo** [comment]
I think this is fixed in https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a7

I add a try catch around these code

**Comment by linonetwo** [comment]
白屏问题我也遇到了，我记在 #71 里了
