### ISSUE TITLE
bug: Error processing argument at index 2, conversion failure from 

### ISSUE THREAD

**Issue by xiakong24** [tiddly-gittly/TiddlyGit-Desktop#62]
```
TypeError: Error processing argument at index 2, conversion failure from 
    at Object.normal (electron/js2c/browser_init.js:81:444)
    at Object.insertItemByType (electron/js2c/browser_init.js:81:1392)
    at Object.a.insert (electron/js2c/browser_init.js:81:3975)
    at Object.a.append (electron/js2c/browser_init.js:81:3639)
    at electron/js2c/browser_init.js:81:5650
    at Array.forEach (<anonymous>)
    at Function.a.buildFromTemplate (electron/js2c/browser_init.js:81:5600)
    at new MenuItem (electron/js2c/browser_init.js:73:587)
    at electron/js2c/browser_init.js:81:5657
    at Array.forEach (<anonymous>)
    at Function.a.buildFromTemplate (electron/js2c/browser_init.js:81:5600)
    at Ie.buildMenu (C:\Users\HuLei\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\main\index.js:2:1591012)
```

---

TiddlyGit 0.4.0
Electron 12.0.6
win32 10.0.19043
Locale: zh-CN

**Comment by linonetwo** [comment]
I think this is fixed in https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a7

I add a try catch around these code
