### ISSUE TITLE
bug: ERR_FAILED (-2) loading 'file://C:\Users\coxcj\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\renderer\main_window\index.html'

### ISSUE THREAD

**Issue by chevyjiang** [tiddly-gittly/TiddlyGit-Desktop#66]
```
Error: ERR_FAILED (-2) loading 'file://C:\Users\coxcj\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\renderer\main_window\index.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:217:1457)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:217:1832)
    at Object.emit (events.js:315:20)
```

---

TiddlyGit 0.4.0
Electron 12.0.6
win32 10.0.19042
Locale: en-US

**Comment by linonetwo** [comment]
Might be fixed in latest prerelease?
