### ISSUE TITLE
bug: 工作区对应的Wiki网页加载失败了，原因有很多，但基本是因为程序Bug ERR_ADDRESS_INVALID http://0.0.0.0:5212/

### ISSUE THREAD

**Issue by Deteriorator** [tiddly-gittly/TiddlyGit-Desktop#78]
## Environment

TiddlyGit 0.4.0
Electron 13.1.4
win32 10.0.19042
Locale: zh-CN

## Description:

打开软件报错

## Steps to Reproduce:

无法显示wiki，如下描述

## Additional Context

```typescript
工作区加载失败错误: 工作区对应的Wiki网页加载失败了，原因有很多，但基本是因为程序Bug ERR_ADDRESS_INVALID http://0.0.0.0:5212/
    at Mn.main [as initializeAllWorkspaceView] (C:\Users\xxxx\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\services\workspacesView\index.ts:81:15)
    at initRendererI18NHandler (C:\Users\xxxx\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\main.ts:117:42)
    at App.<anonymous> (C:\Users\xxxx\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\main.ts:164:11)
```

---

**Comment by linonetwo** [comment]
最新预发布版修复啦

**Comment by linonetwo** [comment]
Fixed in https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a15

Thanks for trying!
