### ISSUE TITLE
bug: 工作区对应的Wiki网页加载失败了，原因有很多，但基本是因为程序Bug ERR_EMPTY_RESPONSE http://0.0.0.0:5212/

### ISSUE THREAD

**Issue by AIlifuk** [tiddly-gittly/TiddlyGit-Desktop#79]
## Environment

TiddlyGit 0.4.0
Electron 13.1.4
win32 10.0.19043
Locale: zh-CN

## Additional Context

```typescript
工作区加载失败错误: 工作区对应的Wiki网页加载失败了，原因有很多，但基本是因为程序Bug ERR_EMPTY_RESPONSE http://0.0.0.0:5212/
    at On.main [as initializeAllWorkspaceView] (C:\Users\Administrator\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\services\workspacesView\index.ts:81:15)
    at initRendererI18NHandler (C:\Users\Administrator\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\main.ts:117:42)
    at App.<anonymous> (C:\Users\Administrator\AppData\Local\TiddlyGit\app-0.4.0\resources\app.asar\.webpack\main\webpack:\TiddlyGit\src\main.ts:164:11)
```

---

**Comment by linonetwo** [comment]
prerelease a9 也有吗，不应该啊

**Comment by Deteriorator** [comment]
> prerelease a9 也有吗，不应该啊

我上午提交的就是a9出现的， 你说已修复，我以为是a10 修复了，就没回复 #78

**Comment by linonetwo** [comment]
好吧，我这次真修复了，等等发个a11.不过我准备把另一个bug一起修了

**Comment by linonetwo** [comment]
Fixed in https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases/tag/v0.4.1-a15
