### ISSUE TITLE
bug: Tiddlywiki booted failed with error Unexpected end of JSON input SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by seaofcomplete** [tiddly-gittly/TiddlyGit-Desktop#81]
版本：0.4.1-a15
平台：win10 2004
在修改条目时，会随机报错
log:
```
Unhandled Error
Error: Tiddlywiki booted failed with error Unexpected end of JSON input SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at $tw.Wiki.application/json (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1621:16)
    at $tw.Wiki.deserializeTiddlers (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1516:23)
    at Object.$tw.loadTiddlersFromFile (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1783:23)
    at Object.$tw.loadTiddlersFromPath (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1835:22)
    at C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1830:40
    at Object.$tw.utils.each (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:126:12)
    at Object.$tw.loadTiddlersFromPath (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:1828:15)
    at Object.$tw.loadWikiTiddlers (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:2116:21)
    at Object.$tw.loadTiddlersNode (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:2207:27)
    at e._subscribe (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/src/services/wiki/wikiWorker.ts:45:19)
    at e._trySubscribe (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/rxjs/dist/cjs/internal/Observable.js:71:25)
    at e.subscribe (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/rxjs/dist/cjs/internal/Observable.js:36:30)
    at next (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/threads/dist/worker/index.js:117:45)
    at Generator.next (<anonymous>)
    at C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/threads/dist/worker/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/threads/dist/worker/index.js:4:12)
    at runFunction (C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/threads/dist/worker/index.js:106:12)
    at C:/Users/{用户名}/AppData/Local/TiddlyGit/app-0.4.1-a15/resources/app.asar.unpacked/.webpack/main/webpack:/TiddlyGit/node_modules/threads/dist/worker/index.js:163:17
```

关闭客户端再开也还会报这个错，在wiki库中删除对应条目才回恢复。

**Comment by linonetwo** [comment]
这个应该是tw的问题，或者是你改了某个重要的内部文件？

如果觉得是tw nodejs版的bug，可以搞个能复现的仓库，去tw那边提bug。

**Comment by linonetwo** [comment]
你改了啥文件呀
